stages:
   - build
   - test

#ABYME cache specifies files that should be saved for later to be used between runs or stages
cache:
   paths:
      - node_modules/

build_app:
   image: node:12
   stage: build
   only:
      - master
   script:
      - npm install
      - npm run build
   artifacts:
      paths:
         - dist/
      expire_in: 1 hour

test_unit:
   image: node:12
   stage: test
   script: 
      - npm run test:unit

test_e2e:
   image: cypress/base:10
   stage: test
   script:
       - npm install
       - $(npm bin)/cypress install
       - $(npm bin)/cypress verify
       - npm run serve &
      # sleep in order to make "npm run serve" start the server in background
       - sleep 20 
       - $(npm bin)/cypress run

