stages:
   - build
   - test

build_app:
   image: node:12
   stage: build
   only:
      - master
   script:
      - npm install
      - npm run build
   cache:
     paths:
       - node_modules/
   artifacts:
      paths:
         - dist/
      expire_in: 1 hour

test_unit:
   image: node:12
   stage: test
   script: 
      - npm install
      - npm run test:unit
